### ISSUE TITLE
Questions about the requirement of environment

### ISSUE THREAD

**Issue by Chuan1997** [tebesu/CollaborativeMemoryNetwork#10]
**Follow the instructions in README, I set tf version to 1.4.0 and dm-sonnet to 1.36, then I ran the code and got this error:**
Traceback (most recent call last):
  File "train.py", line 13, in <module>
    from util.cmn import CollaborativeMemoryNetwork
  File "D:\Study\reproduction\CollaborativeMemoryNetwork-tf\util\cmn.py", line 1, in <module>
    import sonnet as snt
  File "E:\Anaconda\envs\tf1.4\lib\site-packages\sonnet\__init__.py", line 63, in <module>
    _ensure_dependency_available_at_version('tensorflow', '1.8.0')
  File "E:\Anaconda\envs\tf1.4\lib\site-packages\sonnet\__init__.py", line 61, in _ensure_dependency_available_at_version
    (package_name, pkg.__version__, min_version))
SystemError: tensorflow version 1.4.0 is installed, but Sonnet requires at least version 1.8.0.

**Since the sonnet 1.8.0 version is not exist, if I use the sonnet 2.0.0, snt.AbstractModule is not compatiable.
Could you give me some advices?**

**Comment by tebesu** [comment]
Trying using `dm-sonnet==1.25` 

If you have issues with `tensorflow_probability` try version 0.7. Let me know if you still have issues.

**Comment by Chuan1997** [comment]
I re-installed dm-sonnet==1.25, and the version of tensorflow_probability is 0.7.0 under the tf 1.4.0 environment. Then I got this error:
_Traceback (most recent call last):
  File "train.py", line 13, in <module>
    from util.cmn import CollaborativeMemoryNetwork
  File "D:\Study\reproduction\CollaborativeMemoryNetwork-tf\util\cmn.py", line 1, in <module>
    import sonnet as snt
  File "E:\Anaconda\envs\tf1.4\lib\site-packages\sonnet\__init__.py", line 42, in <module>
    from sonnet.python import custom_getters
  File "E:\Anaconda\envs\tf1.4\lib\site-packages\sonnet\python\custom_getters\__init__.py", line 21, in <module>
    from sonnet.python.custom_getters import bayes_by_backprop
  File "E:\Anaconda\envs\tf1.4\lib\site-packages\sonnet\python\custom_getters\bayes_by_backprop.py", line 94, in <module>
    import tensorflow_probability as tfp
  File "E:\Anaconda\envs\tf1.4\lib\site-packages\tensorflow_probability\__init__.py", line 68, in <module>
    _ensure_tf_install()
  File "E:\Anaconda\envs\tf1.4\lib\site-packages\tensorflow_probability\__init__.py", line 65, in _ensure_tf_install
    present=tf.__version__))
ImportError: This version of TensorFlow Probability requires TensorFlow version >= 1.14; Detected an installation of version 1.4.0. Please upgrade TensorFlow to proceed._

**It seems that tensorflow_probability doesn't have a match-up version for tf 1.4**(after I checked release notes _https://github.com/tensorflow/probability/tags_)

**Comment by tebesu** [comment]
Try tensorflow version 1.14

**Comment by Chuan1997** [comment]
Problem solved. Thanks.
