### ISSUE TITLE
train.py crash InvalidArgumentError

### ISSUE THREAD

**Issue by MaurizioFD** [tebesu/CollaborativeMemoryNetwork#2]
Dear authors,

I was trying to run your algorithm. While pretrain.py runs until the end, train.py, with your own configuration, crashes very soon with an InvalidArgumentError

I am using tensorflow 1.8.0, sonnet 1.23 and python 3.6

The console oputput is the following:

[INFO:tensorflow]<info>:116: 

{
  "batch_size": 128,
  "decay_rate": 0.9,
  "embed_size": 50,
  "filename": "data/citeulike-a.npz",
  "grad_clip": 5.0,
  "hops": 2,
  "item_count": "16980",
  "l2": 0.1,
  "learning_rate": 0.001,
  "logdir": "result/004/",
  "max_neighbors": 311,
  "neg_count": 4,
  "optimizer": "rmsprop",
  "optimizer_params": "{'momentum': 0.9, 'decay': 0.9}",
  "pretrain": "pretrain/citeulike-a_e50.npz",
  "save_directory": "result/004/",
  "tol": 1e-05,
  "user_count": "5551"
}

[WARNING:tensorflow]<warning>:126: From /home/ubuntu/Scaricati/CollaborativeMemoryNetwork-master/util/layers.py:250: get_or_create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.get_or_create_global_step
[INFO:tensorflow]<info>:116: Creating Hop Mapping 2 with <function relu at 0x7f6033936400>
[INFO:tensorflow]<info>:116: Creating Hop Mapping 2 with <function relu at 0x7f6033936400>
[WARNING:tensorflow]<warning>:126: From train.py:83: Supervisor.__init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
2018-09-18 10:31:07.033201: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
[INFO:tensorflow]<info>:116: Running local_init_op.
[INFO:tensorflow]<info>:116: Done running local_init_op.
[INFO:tensorflow]<info>:116: Starting standard services.
[INFO:tensorflow]<info>:116: Saving checkpoint to path result/004/model.ckpt
[INFO:tensorflow]<info>:116: Starting queue runners.
[INFO:tensorflow]<info>:116: Loading Pretrained Embeddings.... from pretrain/citeulike-a_e50.npz

  0%|          | 0/6232 [00:00<?, ?it/s]
[0] Loss: 10.9797 » » » » :   0%|          | 0/6232 [00:00<?, ?it/s]
[0] Loss: 10.9797 » » » » :   0%|          | 1/6232 [00:00<54:19,  1.91it/s]
[0] Loss: 10.9669 » » » » :   0%|          | 1/6232 [00:00<1:04:38,  1.61it/s]
[0] Loss: 10.9458 » » » » :   0%|          | 1/6232 [00:00<1:24:32,  1.23it/s]
[0] Loss: 10.9458 » » » » :   0%|          | 3/6232 [00:00<28:10,  3.68it/s]  Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/DL_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/ubuntu/anaconda3/envs/DL_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/ubuntu/anaconda3/envs/DL_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[126,0] = 12178 is not in [0, 5551)
	 [[Node: MemoryOutput_2/embedding_lookup = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@Optimizer/ApplyGradients/update_MemoryOutput/embeddings/ApplyRMSProp"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](MemoryOutput/embeddings/read, _arg_NeighborhoodNeg_0_5, Optimizer/gradients/MemoryOutput_1/embedding_lookup_grad/concat/axis)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 116, in <module>
    batch_loss, _ = sess.run([model.loss, model.train], feed)
  File "/home/ubuntu/anaconda3/envs/DL_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/ubuntu/anaconda3/envs/DL_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ubuntu/anaconda3/envs/DL_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/ubuntu/anaconda3/envs/DL_env/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[126,0] = 12178 is not in [0, 5551)
	 [[Node: MemoryOutput_2/embedding_lookup = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@Optimizer/ApplyGradients/update_MemoryOutput/embeddings/ApplyRMSProp"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](MemoryOutput/embeddings/read, _arg_NeighborhoodNeg_0_5, Optimizer/gradients/MemoryOutput_1/embedding_lookup_grad/concat/axis)]]

Caused by op 'MemoryOutput_2/embedding_lookup', defined at:
  File "train.py", line 80, in <module>
    model = CollaborativeMemoryNetwork(config)
  File "/home/ubuntu/Scaricati/CollaborativeMemoryNetwork-master/util/cmn.py", line 42, in __init__
    self._construct()
  File "/home/ubuntu/Scaricati/CollaborativeMemoryNetwork-master/util/cmn.py", line 69, in _construct
    self.user_output(self.input_neighborhoods_negative),
  File "/home/ubuntu/anaconda3/envs/DL_env/lib/python3.6/site-packages/sonnet/python/modules/base.py", line 389, in __call__
    outputs, subgraph_name_scope = self._template(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/DL_env/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 455, in __call__
    result = self._call_func(args, kwargs)
  File "/home/ubuntu/anaconda3/envs/DL_env/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 400, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/DL_env/lib/python3.6/site-packages/sonnet/python/modules/base.py", line 246, in _build_wrapper
    output = self._build(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/DL_env/lib/python3.6/site-packages/sonnet/python/modules/embed.py", line 166, in _build
    self._embeddings, ids, name="embedding_lookup")
  File "/home/ubuntu/anaconda3/envs/DL_env/lib/python3.6/site-packages/tensorflow/python/ops/embedding_ops.py", line 308, in embedding_lookup
    transform_fn=None)
  File "/home/ubuntu/anaconda3/envs/DL_env/lib/python3.6/site-packages/tensorflow/python/ops/embedding_ops.py", line 131, in _embedding_lookup_and_transform
    result = _clip(array_ops.gather(params[0], ids, name=name),
  File "/home/ubuntu/anaconda3/envs/DL_env/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 2736, in gather
    return gen_array_ops.gather_v2(params, indices, axis, name=name)
  File "/home/ubuntu/anaconda3/envs/DL_env/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3065, in gather_v2
    "GatherV2", params=params, indices=indices, axis=axis, name=name)
  File "/home/ubuntu/anaconda3/envs/DL_env/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/ubuntu/anaconda3/envs/DL_env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/ubuntu/anaconda3/envs/DL_env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): indices[126,0] = 12178 is not in [0, 5551)
	 [[Node: MemoryOutput_2/embedding_lookup = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@Optimizer/ApplyGradients/update_MemoryOutput/embeddings/ApplyRMSProp"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](MemoryOutput/embeddings/read, _arg_NeighborhoodNeg_0_5, Optimizer/gradients/MemoryOutput_1/embedding_lookup_grad/concat/axis)]]

**Comment by tebesu** [comment]
@MaurizioFD I am unable to reproduce this error. Have you modified the code? The loss should be between 0-1 and yours shows 10?

**Comment by MaurizioFD** [comment]
@tebesu Thank you for the reply
I have not modified the code, I have just cloned the repo and executed train.py with the parameters you indicate. The only thing I have done is to create the folder "result".

pretrain.py works fine, I am able to generate a new pretrain npz file and I see a loss value going below 0.01, but still train.py crashes after a few seconds. I have noticed that the error arises in the "# Train Loop" part (lines 96-123). If I comment that part the evaluation of the pretrained model concludes and I see the results for HR and NDCG, they are however in the range of 0.0x.

I have also tried using another pc with ubuntu and a clean installation of tensorflow and sonnet.

**Comment by tebesu** [comment]
@MaurizioFD 

Does the same error occur when you use the provided pretrained model?

**Comment by MaurizioFD** [comment]
@tebesu Yes it does

**Comment by tebesu** [comment]
@MaurizioFD 

Since I am unable to reproduce this error I cannot offer much support other than point you in a a direction. 

The error appears to be coming from a bad user index in the neighborhood `indices[126,0] = 12178 is not in [0, 5551)` which seems like it could be an index from an item which is weird. Try examining it with a debugger. I can try and help you but overall since I am unable to reproduce it will be limited.

**Comment by sshzhang** [comment]
@MaurizioFD  @tebesu    
 I also meets the same problems , I am using tensorflow 1.11.0, sonnet 1.23 and python 3.6, 

error is consoled in follow.


[INFO:tensorflow]<info>:115: 

{
  "batch_size": 128,
  "decay_rate": 0.9,
  "embed_size": 50,
  "filename": "data/citeulike-a.npz",
  "grad_clip": 5.0,
  "hops": 2,
  "item_count": "16980",
  "l2": 0.1,
  "learning_rate": 0.001,
  "logdir": "result/003/",
  "max_neighbors": 311,
  "neg_count": 4,
  "optimizer": "rmsprop",
  "optimizer_params": "{'momentum': 0.9, 'decay': 0.9}",
  "pretrain": "pretrain/citeulike-a_e50.npz",
  "save_directory": "result/003/",
  "tol": 1e-05,
  "user_count": "5551"
}


[WARNING:tensorflow]<warning>:125: From /home/zxj/PycharmProjects/CollaborativeMemoryNetwork/util/layers.py:250: get_or_create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.get_or_create_global_step
[INFO:tensorflow]<info>:115: Creating Hop Mapping 2 with <function relu at 0x7fe21277ad90>
[INFO:tensorflow]<info>:115: Creating Hop Mapping 2 with <function relu at 0x7fe21277ad90>
[WARNING:tensorflow]<warning>:125: From /home/zxj/PycharmProjects/CollaborativeMemoryNetwork/train.py:83: Supervisor.__init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
[INFO:tensorflow]<info>:115: Running local_init_op.
[INFO:tensorflow]<info>:115: Done running local_init_op.
[INFO:tensorflow]<info>:115: Starting standard services.
[INFO:tensorflow]<info>:115: Saving checkpoint to path result/003/model.ckpt
[INFO:tensorflow]<info>:115: Starting queue runners.
[INFO:tensorflow]<info>:115: Loading Pretrained Embeddings.... from pretrain/citeulike-a_e50.npz
[0] Loss: 10.3205 » » » » :   0%|          | 22/6232 [00:02<09:16, 11.15it/s]Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1292, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1277, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1367, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[78,0] = 11902 is not in [0, 5551)
	 [[{{node MemoryEmbed_2/embedding_lookup}} = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@Optimizer/ApplyGradients/update_MemoryEmbed/embeddings/ApplyRMSProp"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](MemoryEmbed/embeddings/read, _arg_NeighborhoodNeg_0_5, Optimizer/gradients/MemoryEmbed_1/embedding_lookup_grad/concat/axis)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxj/PycharmProjects/CollaborativeMemoryNetwork/train.py", line 116, in <module>
    batch_loss, _ = sess.run([model.loss, model.train], feed)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1286, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[78,0] = 11902 is not in [0, 5551)
	 [[{{node MemoryEmbed_2/embedding_lookup}} = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@Optimizer/ApplyGradients/update_MemoryEmbed/embeddings/ApplyRMSProp"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](MemoryEmbed/embeddings/read, _arg_NeighborhoodNeg_0_5, Optimizer/gradients/MemoryEmbed_1/embedding_lookup_grad/concat/axis)]]

Caused by op 'MemoryEmbed_2/embedding_lookup', defined at:
  File "/home/zxj/PycharmProjects/CollaborativeMemoryNetwork/train.py", line 80, in <module>
    model = CollaborativeMemoryNetwork(config)
  File "/home/zxj/PycharmProjects/CollaborativeMemoryNetwork/util/cmn.py", line 42, in __init__
    self._construct()
  File "/home/zxj/PycharmProjects/CollaborativeMemoryNetwork/util/cmn.py", line 68, in _construct
    self.user_memory(self.input_neighborhoods_negative),
  File "/usr/local/lib/python3.6/dist-packages/sonnet/python/modules/base.py", line 389, in __call__
    outputs, subgraph_name_scope = self._template(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/template.py", line 360, in __call__
    return self._call_func(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/template.py", line 306, in _call_func
    result = self._func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sonnet/python/modules/base.py", line 246, in _build_wrapper
    output = self._build(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sonnet/python/modules/embed.py", line 166, in _build
    self._embeddings, ids, name="embedding_lookup")
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/embedding_ops.py", line 313, in embedding_lookup
    transform_fn=None)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/embedding_ops.py", line 133, in _embedding_lookup_and_transform
    result = _clip(array_ops.gather(params[0], ids, name=name),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/array_ops.py", line 2669, in gather
    return gen_array_ops.gather_v2(params, indices, axis, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3232, in gather_v2
    "GatherV2", params=params, indices=indices, axis=axis, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3272, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): indices[78,0] = 11902 is not in [0, 5551)
	 [[{{node MemoryEmbed_2/embedding_lookup}} = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@Optimizer/ApplyGradients/update_MemoryEmbed/embeddings/ApplyRMSProp"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](MemoryEmbed/embeddings/read, _arg_NeighborhoodNeg_0_5, Optimizer/gradients/MemoryEmbed_1/embedding_lookup_grad/concat/axis)]]

Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1292, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1277, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1367, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[78,0] = 11902 is not in [0, 5551)
	 [[{{node MemoryEmbed_2/embedding_lookup}} = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@Optimizer/ApplyGradients/update_MemoryEmbed/embeddings/ApplyRMSProp"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](MemoryEmbed/embeddings/read, _arg_NeighborhoodNeg_0_5, Optimizer/gradients/MemoryEmbed_1/embedding_lookup_grad/concat/axis)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxj/PycharmProjects/CollaborativeMemoryNetwork/train.py", line 116, in <module>
    batch_loss, _ = sess.run([model.loss, model.train], feed)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1286, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[78,0] = 11902 is not in [0, 5551)
	 [[{{node MemoryEmbed_2/embedding_lookup}} = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@Optimizer/ApplyGradients/update_MemoryEmbed/embeddings/ApplyRMSProp"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](MemoryEmbed/embeddings/read, _arg_NeighborhoodNeg_0_5, Optimizer/gradients/MemoryEmbed_1/embedding_lookup_grad/concat/axis)]]

Caused by op 'MemoryEmbed_2/embedding_lookup', defined at:
  File "/home/zxj/PycharmProjects/CollaborativeMemoryNetwork/train.py", line 80, in <module>
    model = CollaborativeMemoryNetwork(config)
  File "/home/zxj/PycharmProjects/CollaborativeMemoryNetwork/util/cmn.py", line 42, in __init__
    self._construct()
  File "/home/zxj/PycharmProjects/CollaborativeMemoryNetwork/util/cmn.py", line 68, in _construct
    self.user_memory(self.input_neighborhoods_negative),
  File "/usr/local/lib/python3.6/dist-packages/sonnet/python/modules/base.py", line 389, in __call__
    outputs, subgraph_name_scope = self._template(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/template.py", line 360, in __call__
    return self._call_func(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/template.py", line 306, in _call_func
    result = self._func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sonnet/python/modules/base.py", line 246, in _build_wrapper
    output = self._build(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sonnet/python/modules/embed.py", line 166, in _build
    self._embeddings, ids, name="embedding_lookup")
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/embedding_ops.py", line 313, in embedding_lookup
    transform_fn=None)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/embedding_ops.py", line 133, in _embedding_lookup_and_transform
    result = _clip(array_ops.gather(params[0], ids, name=name),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/array_ops.py", line 2669, in gather
    return gen_array_ops.gather_v2(params, indices, axis, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3232, in gather_v2
    "GatherV2", params=params, indices=indices, axis=axis, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3272, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): indices[78,0] = 11902 is not in [0, 5551)
	 [[{{node MemoryEmbed_2/embedding_lookup}} = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@Optimizer/ApplyGradients/update_MemoryEmbed/embeddings/ApplyRMSProp"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](MemoryEmbed/embeddings/read, _arg_NeighborhoodNeg_0_5, Optimizer/gradients/MemoryEmbed_1/embedding_lookup_grad/concat/axis)]]

**Comment by tebesu** [comment]
I will look into the issue. It runs fine on GPU but throws an error when running on CPU. 

Could @MaurizioFD or @sshzhang confirm running the GPU works fine?

**Comment by jxz542189** [comment]
the same error:
[INFO:tensorflow]<info>:115: Loading Pretrained Embeddings.... from /root/PycharmProjects/CollaborativeMemoryNetwork/pretrain/citeulike-a_e50.npz
[0] Loss: 11.0247 » » » » :   0%|          | 4/6232 [00:51<22:04:12, 12.76s/it]Traceback (most recent call last):
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[107,0] = 12178 is not in [0, 5551)
	 [[Node: MemoryOutput_2/embedding_lookup = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@Optimizer/ApplyGradients/update_MemoryOutput/embeddings/ApplyRMSProp"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](MemoryOutput/embeddings/read, _arg_NeighborhoodNeg_0_5, Optimizer/gradients/MemoryOutput_1/embedding_lookup_grad/concat/axis)]]

During handling of the above exception, another exception occurred:

**Comment by simon19891101** [comment]
Confronted the same issue while using CPU and problem got resolved after switched to GPU as mentioned by @tebesu. Keen to explore the potential reasons behind if the model performs well on my dataset.

**Comment by tebesu** [comment]
Thanks for reminding me about this issue. @simon19891101 

I refactored the original code used to report the experiments since it was very messy. In the original version I presampled the negative items and stored them in a HD5 file so this issue does not arise in the original version. This version the negatives are sampled on the fly.


The problem stems from calling self.item_users_list[index] which is a defaultdict. In some cases, the index does not exist but still executes the else statement without throwing an exception. 

```
self.item_users_list = defaultdict(list)

# ....

if len(self.item_users[neg_item_idx]) > 0:
    neg_length[idx] = len(self.item_users[neg_item_idx])
    neg_neighbor[idx, :neg_length[idx]] = self.item_users_list[neg_item_idx]
else:
    # Length defaults to 1
    neg_length[idx] = 1
    neg_neighbor[idx, 0] = neg_item_idx
```

I will upload a fix tomorrow.

**Comment by tebesu** [comment]
I pushed an update. Please see if this also works for you.

**Comment by simon19891101** [comment]
Awesome! Works for CPU now. Much appreaciated.
